### ISSUE TITLE
Game freezing while querying

### ISSUE THREAD

**Issue by nichtDanger** [Aruloci/WynnVentory#23]
hey, the mod is really good, thanks for that. 
However, the game always hangs briefly during the query when hovering over the item. Would it be possible to perform the query asynchronously to avoid something like this?

**Comment by Aruloci** [comment]
Hi, thank you for your feedback! This is something that will be fixed in the next update. Price information will be rendered in a seperate tooltip and the query is performed asynchronously. This way the mod does no longer impact the main thread.

**Comment by Aruloci** [comment]
Fix implemented
